wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/BGs/whiteBG.jxl
    fit_mode = cover
}

wallpaper {
    monitor = eDP-2
    path = ~/Pictures/BGs/whiteBG.jxl
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = ~/Pictures/BGs/whiteBG.jxl
    fit_mode = cover
}

splash = false
